export const userProfile = {
  firstName: "Kevin",
  goal: "Skaten, Hund, Klimmzug und sauberer Wiedereinstieg in mehr Belastbarkeit",
};

const guide = {
  walkWarmup:
    "Starte mit lockerem Gehen, damit Kreislauf, Fussgelenke und Beine ruhig warm werden.",
  jogInterval:
    "Locker joggen. Du solltest noch ruhig atmen und dich nebenbei unterhalten koennen.",
  walkInterval:
    "Gehe bewusst langsam genug, damit Puls und Atmung wieder runterkommen.",
  cooldownWalk:
    "Zum Abschluss locker ausgehen und die Atmung beruhigen.",
  mobilityFlow:
    "Bewege Schultern, Huefte, Ruecken und Nacken langsam durch schmerzfreie Bewegungen. Kein Dehnen mit Gewalt.",
  plank:
    "Stuetz dich auf Unterarme oder Haende. Bauch fest, Po leicht angespannt und den Koerper gerade halten.",
  sidePlank:
    "Seitlicher Stuetz auf Unterarm. Huefte anheben und den Koerper moeglichst gerade halten.",
  gluteBridge:
    "Rueckenlage, Fuesse aufstellen, dann das Becken anheben bis Knie, Huefte und Schultern eine Linie bilden.",
  squat:
    "Hueftbreit stehen, Po nach hinten unten fuehren und kontrolliert wieder aufstehen.",
  gobletSquat:
    "Eine Hantel oder Kettlebell vor der Brust halten und dann eine saubere Kniebeuge machen.",
  rdl:
    "Romanian Deadlift: Mit leicht gebeugten Knien die Huefte nach hinten schieben, Ruecken neutral halten und Gewicht nah am Bein fuehren.",
  row:
    "Rudern mit Hanteln oder Band: Schulterblaetter nach hinten ziehen und Ellbogen dicht am Koerper fuehren.",
  deadHang:
    "Einfach an der Stange haengen. Schultern lang lassen, Griff fest halten und nur so lange wie sauber moeglich haengen.",
  lunge:
    "Einen grossen Schritt setzen, hinten tief absenken und kontrolliert wieder hochdruecken.",
  splitSquat:
    "Versetzter Stand wie beim Ausfallschritt, aber auf der Stelle. Gerade absenken und wieder hochdruecken.",
  inclinePushup:
    "Liegestuetz mit den Haenden erhoeht auf Bank, Tisch oder Kiste. Koerper bleibt als Linie stabil.",
  pushup:
    "Haende unter den Schultern, Koerper fest, Brust kontrolliert senken und wieder hochdruecken.",
  scapulaPull:
    "An der Stange haengen und nur die Schulterblaetter nach unten hinten ziehen, ohne die Arme stark zu beugen.",
  negativePullup:
    "Oben in der Klimmzugposition starten und dann 3 bis 5 Sekunden moeglichst langsam nach unten ablassen.",
  balanceBoard:
    "Ruhig auf dem Balance Board stehen und kleine Ausgleichsbewegungen machen. Fokus auf Kontrolle statt Tempo.",
  easyStretch:
    "Nur leicht lockern und dehnen, ohne in Schmerz oder starkes Ziehen zu gehen.",
  testRun:
    "Ruhiger Testlauf. Tempo so waehlen, dass du dich die ganze Zeit kontrolliert fuehlst.",
  walkOnly:
    "Nur die Gassi-Runde oder einen lockeren Spaziergang machen. Kein Zusatzdruck.",
};

function makeExercise(sessionId, slug, name, prescription, description) {
  return {
    id: `${sessionId}-${slug}`,
    name,
    prescription,
    description,
  };
}

function buildSession(config) {
  return {
    id: config.id,
    title: config.title,
    focus: config.focus,
    duration: config.duration,
    description: config.description,
    exercises: config.exercises.map((exercise) =>
      makeExercise(
        config.id,
        exercise.slug,
        exercise.name,
        exercise.prescription,
        exercise.description,
      ),
    ),
  };
}

const sessionBlueprints = [
  {
    id: "w1-mon",
    week: 1,
    dayLabel: "Mo",
    fullLabel: "Montag",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 30,
    status: "done",
    description:
      "Locker in Woche 1 starten. Du solltest durch die Nase atmen koennen und dich nicht hetzen.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "4 x 1 Min", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "4 x 4 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w1-tue",
    week: 1,
    dayLabel: "Di",
    fullLabel: "Dienstag",
    title: "Mobility + leicht",
    focus: "Beweglichkeit + Rumpf",
    duration: 15,
    status: "done",
    description:
      "Leichte Mobilisation und etwas Rumpfspannung, ohne Muskelkater zu provozieren.",
    planTitle: "Mobility + leicht",
    exercises: [
      { slug: "mobility", name: "Mobility Flow", prescription: "10 Min", description: guide.mobilityFlow },
      { slug: "plank", name: "Plank", prescription: "2 x 20 Sek", description: guide.plank },
      { slug: "bridge", name: "Glute Bridge", prescription: "2 x 10", description: guide.gluteBridge },
    ],
  },
  {
    id: "w1-wed",
    week: 1,
    dayLabel: "Mi",
    fullLabel: "Mittwoch",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 30,
    status: "open",
    isToday: true,
    description: "Sehr locker bleiben und die Intervalle ruhig und gleichmaessig laufen.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "5 x 1 Min", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "5 x 3 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w1-thu",
    week: 1,
    dayLabel: "Do",
    fullLabel: "Donnerstag",
    title: "Kraft A",
    focus: "Kraft Unterkoerper + Zug",
    duration: 24,
    status: "open",
    description: "Sauber trainieren bei RPE 5 bis 6. Technik geht klar vor Tempo.",
    planTitle: "Kraft A",
    exercises: [
      { slug: "squat", name: "Kniebeugen", prescription: "2 x 8", description: guide.squat },
      { slug: "rdl", name: "RDL mit Hanteln", prescription: "2 x 8", description: guide.rdl },
      { slug: "row", name: "Rudern", prescription: "2 x 8", description: guide.row },
      { slug: "hang", name: "Dead Hang", prescription: "2 x 20 Sek", description: guide.deadHang },
    ],
  },
  {
    id: "w1-fri",
    week: 1,
    dayLabel: "Fr",
    fullLabel: "Freitag",
    title: "Pause / Spaziergang",
    focus: "Regeneration",
    duration: 10,
    status: "pause",
    description: "Nur lockere Bewegung. Kein Training erzwingen.",
    planTitle: "Pause / Spaziergang",
    exercises: [
      { slug: "walk", name: "Gassi-Runde", prescription: "Locker", description: guide.walkOnly },
      { slug: "stretch", name: "Optionale Mobility", prescription: "5 Min", description: guide.mobilityFlow },
    ],
  },
  {
    id: "w1-sat",
    week: 1,
    dayLabel: "Sa",
    fullLabel: "Samstag",
    title: "Walk-Run mit Hund",
    focus: "Grundlagenausdauer",
    duration: 35,
    status: "open",
    description: "Eher Gehfokus. Wenn du trabst, dann nur ganz locker.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "walk", name: "Zuegig gehen", prescription: "30 bis 35 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Leichtes Traben optional", prescription: "3 x 30 Sek", description: guide.jogInterval },
    ],
  },
  {
    id: "w1-sun",
    week: 1,
    dayLabel: "So",
    fullLabel: "Sonntag",
    title: "Kraft B",
    focus: "Kraft Beine + Druck + Klimmzug-Basis",
    duration: 24,
    status: "open",
    description: "Sauber arbeiten, nicht auspowern.",
    planTitle: "Kraft B",
    exercises: [
      { slug: "lunge", name: "Ausfallschritte", prescription: "2 x 6 je Bein", description: guide.lunge },
      { slug: "pushup", name: "Liegestuetze erhoeht", prescription: "2 x 8", description: guide.inclinePushup },
      { slug: "scapula", name: "Scapula Pulls", prescription: "2 x 5", description: guide.scapulaPull },
      { slug: "bridge", name: "Glute Bridge", prescription: "2 x 10", description: guide.gluteBridge },
    ],
  },
  {
    id: "w2-mon",
    week: 2,
    dayLabel: "Mo",
    fullLabel: "Montag",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 27,
    status: "open",
    description: "Locker bleiben, trotz etwas laengerer Laufintervalle.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "4 x 90 Sek", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "4 x 3 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w2-tue",
    week: 2,
    dayLabel: "Di",
    fullLabel: "Dienstag",
    title: "Mobility + Balance",
    focus: "Beweglichkeit + Balance",
    duration: 17,
    status: "open",
    description: "Ruhig arbeiten und die Fuss- und Beinachse bewusst kontrollieren.",
    planTitle: "Mobility + Balance",
    exercises: [
      { slug: "mobility", name: "Mobility Flow", prescription: "10 bis 12 Min", description: guide.mobilityFlow },
      { slug: "balance", name: "Balance Board", prescription: "5 Min", description: guide.balanceBoard },
    ],
  },
  {
    id: "w2-wed",
    week: 2,
    dayLabel: "Mi",
    fullLabel: "Mittwoch",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 27,
    status: "open",
    description: "Leicht laufen, nicht jagen.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "5 x 90 Sek", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "5 x 2,5 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w2-thu",
    week: 2,
    dayLabel: "Do",
    fullLabel: "Donnerstag",
    title: "Kraft A",
    focus: "Kraft Unterkoerper + Zug",
    duration: 28,
    status: "open",
    description: "Etwas mehr als Woche 1, aber noch kontrolliert.",
    planTitle: "Kraft A",
    exercises: [
      { slug: "squat", name: "Kniebeugen", prescription: "3 x 8", description: guide.squat },
      { slug: "rdl", name: "RDL", prescription: "3 x 8", description: guide.rdl },
      { slug: "row", name: "Rudern", prescription: "3 x 8", description: guide.row },
      { slug: "hang", name: "Dead Hang", prescription: "2 x 25 Sek", description: guide.deadHang },
    ],
  },
  {
    id: "w2-fri",
    week: 2,
    dayLabel: "Fr",
    fullLabel: "Freitag",
    title: "Pause / Spaziergang",
    focus: "Regeneration",
    duration: 10,
    status: "pause",
    description: "Nur Gassi-Runde und bewusst regenerieren.",
    planTitle: "Pause / Spaziergang",
    exercises: [
      { slug: "walk", name: "Gassi-Runde", prescription: "Locker", description: guide.walkOnly },
    ],
  },
  {
    id: "w2-sat",
    week: 2,
    dayLabel: "Sa",
    fullLabel: "Samstag",
    title: "Walk-Run mit Hund",
    focus: "Grundlagenausdauer",
    duration: 38,
    status: "open",
    description: "Viel gehen, lockeres Traben nur als kurzer Zusatz.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "walk", name: "Zuegig gehen", prescription: "30 bis 40 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Lockeres Traben", prescription: "4 x 20 Sek", description: guide.jogInterval },
    ],
  },
  {
    id: "w2-sun",
    week: 2,
    dayLabel: "So",
    fullLabel: "Sonntag",
    title: "Kraft B",
    focus: "Kraft Beine + Druck + Klimmzug-Basis",
    duration: 26,
    status: "open",
    description: "Kontrolliert arbeiten und jede Wiederholung sauber fuehren.",
    planTitle: "Kraft B",
    exercises: [
      { slug: "split", name: "Split Squats", prescription: "2 x 8 je Bein", description: guide.splitSquat },
      { slug: "pushup", name: "Liegestuetze erhoeht", prescription: "2 x 8", description: guide.inclinePushup },
      { slug: "scapula", name: "Scapula Pulls", prescription: "3 x 5", description: guide.scapulaPull },
      { slug: "negative", name: "Negative Klimmzuege", prescription: "2 x 3", description: guide.negativePullup },
    ],
  },
  {
    id: "w3-mon",
    week: 3,
    dayLabel: "Mo",
    fullLabel: "Montag",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 30,
    status: "open",
    description: "Locker bis moderat, aber weiterhin kontrolliert.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "4 x 2 Min", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "4 x 3 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w3-tue",
    week: 3,
    dayLabel: "Di",
    fullLabel: "Dienstag",
    title: "Mobility + Core",
    focus: "Beweglichkeit + Rumpf",
    duration: 16,
    status: "open",
    description: "Leicht bleiben, aber den Rumpf bewusst ansteuern.",
    planTitle: "Mobility + Core",
    exercises: [
      { slug: "mobility", name: "Mobility Flow", prescription: "10 Min", description: guide.mobilityFlow },
      { slug: "sideplank", name: "Side Plank", prescription: "3 x 20 Sek", description: guide.sidePlank },
      { slug: "bridge", name: "Glute Bridge", prescription: "2 x 10", description: guide.gluteBridge },
    ],
  },
  {
    id: "w3-wed",
    week: 3,
    dayLabel: "Mi",
    fullLabel: "Mittwoch",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 27,
    status: "open",
    description: "Stabil und gleichmaessig laufen.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "4 x 2 Min", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "4 x 2,5 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w3-thu",
    week: 3,
    dayLabel: "Do",
    fullLabel: "Donnerstag",
    title: "Kraft A",
    focus: "Kraft Unterkoerper + Zug",
    duration: 30,
    status: "open",
    description: "RPE 6, also fordernd, aber mit Reserven.",
    planTitle: "Kraft A",
    exercises: [
      { slug: "squat", name: "Kniebeugen", prescription: "3 x 10", description: guide.squat },
      { slug: "rdl", name: "RDL", prescription: "3 x 8", description: guide.rdl },
      { slug: "row", name: "Rudern", prescription: "3 x 10", description: guide.row },
      { slug: "hang", name: "Dead Hang", prescription: "3 x 20 bis 30 Sek", description: guide.deadHang },
    ],
  },
  {
    id: "w3-fri",
    week: 3,
    dayLabel: "Fr",
    fullLabel: "Freitag",
    title: "Pause / Spaziergang",
    focus: "Regeneration",
    duration: 10,
    status: "pause",
    description: "Nur Gassi-Runde, sonst Erholung.",
    planTitle: "Pause / Spaziergang",
    exercises: [
      { slug: "walk", name: "Gassi-Runde", prescription: "Locker", description: guide.walkOnly },
    ],
  },
  {
    id: "w3-sat",
    week: 3,
    dayLabel: "Sa",
    fullLabel: "Samstag",
    title: "Walk-Run mit Hund",
    focus: "Grundlagenausdauer",
    duration: 28,
    status: "open",
    description: "Locker bleiben und eher einen guten Rhythmus als Tempo suchen.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "walk", name: "Zuegig gehen", prescription: "20 bis 25 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Lockeres Traben", prescription: "5 x 30 Sek", description: guide.jogInterval },
    ],
  },
  {
    id: "w3-sun",
    week: 3,
    dayLabel: "So",
    fullLabel: "Sonntag",
    title: "Kraft B",
    focus: "Kraft Beine + Druck + Klimmzug-Basis",
    duration: 30,
    status: "open",
    description: "Sauber arbeiten und nur dann normal tiefere Liegestuetze machen, wenn die Form stabil bleibt.",
    planTitle: "Kraft B",
    exercises: [
      { slug: "lunge", name: "Ausfallschritte", prescription: "3 x 8 je Bein", description: guide.lunge },
      { slug: "pushup", name: "Liegestuetze erhoeht oder normal", prescription: "3 x 8", description: guide.pushup },
      { slug: "scapula", name: "Scapula Pulls", prescription: "3 x 5", description: guide.scapulaPull },
      { slug: "negative", name: "Negative Klimmzuege", prescription: "3 x 3", description: guide.negativePullup },
    ],
  },
  {
    id: "w4-mon",
    week: 4,
    dayLabel: "Mo",
    fullLabel: "Montag",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 32,
    status: "open",
    description: "Moderates Tempo, aber weiter kontrolliert.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "4 x 3 Min", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "4 x 2,5 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w4-tue",
    week: 4,
    dayLabel: "Di",
    fullLabel: "Dienstag",
    title: "Mobility + Balance",
    focus: "Beweglichkeit + Balance",
    duration: 18,
    status: "open",
    description: "Leichter Tag mit Fokus auf Kontrolle und Beweglichkeit.",
    planTitle: "Mobility + Balance",
    exercises: [
      { slug: "mobility", name: "Mobility Flow", prescription: "10 Min", description: guide.mobilityFlow },
      { slug: "balance", name: "Balance Board", prescription: "5 bis 8 Min", description: guide.balanceBoard },
    ],
  },
  {
    id: "w4-wed",
    week: 4,
    dayLabel: "Mi",
    fullLabel: "Mittwoch",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 31,
    status: "open",
    description: "Kontrolliert laufen, nicht hetzen.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "3 x 4 Min", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "3 x 3 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w4-thu",
    week: 4,
    dayLabel: "Do",
    fullLabel: "Donnerstag",
    title: "Kraft A",
    focus: "Kraft Unterkoerper + Zug",
    duration: 30,
    status: "open",
    description: "RPE 6 bis 7. Qualitaet vor Menge.",
    planTitle: "Kraft A",
    exercises: [
      { slug: "goblet", name: "Goblet Squat", prescription: "3 x 10", description: guide.gobletSquat },
      { slug: "rdl", name: "RDL", prescription: "3 x 10", description: guide.rdl },
      { slug: "row", name: "Rudern", prescription: "3 x 10", description: guide.row },
      { slug: "hang", name: "Dead Hang", prescription: "3 x 30 Sek", description: guide.deadHang },
    ],
  },
  {
    id: "w4-fri",
    week: 4,
    dayLabel: "Fr",
    fullLabel: "Freitag",
    title: "Pause / Spaziergang",
    focus: "Regeneration",
    duration: 12,
    status: "pause",
    description: "Locker gehen und nur entspannt dehnen.",
    planTitle: "Pause / Spaziergang",
    exercises: [
      { slug: "walk", name: "Gassi-Runde", prescription: "Locker", description: guide.walkOnly },
      { slug: "stretch", name: "Lockeres Dehnen", prescription: "Kurz", description: guide.easyStretch },
    ],
  },
  {
    id: "w4-sat",
    week: 4,
    dayLabel: "Sa",
    fullLabel: "Samstag",
    title: "Walk-Run mit Hund",
    focus: "Erholung + Bewegung",
    duration: 40,
    status: "open",
    description: "Erholungsorientierter Tag mit viel Gehen.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "walk", name: "Lockeres Gehen", prescription: "35 bis 45 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Traben optional", prescription: "3 x 1 Min", description: guide.jogInterval },
    ],
  },
  {
    id: "w4-sun",
    week: 4,
    dayLabel: "So",
    fullLabel: "Sonntag",
    title: "Kraft B",
    focus: "Kraft Beine + Druck + Klimmzug-Basis",
    duration: 30,
    status: "open",
    description: "Qualitaet vor Menge und sauberer Bewegungsablauf.",
    planTitle: "Kraft B",
    exercises: [
      { slug: "split", name: "Split Squats", prescription: "3 x 8", description: guide.splitSquat },
      { slug: "pushup", name: "Liegestuetze", prescription: "3 x 8", description: guide.pushup },
      { slug: "scapula", name: "Scapula Pulls", prescription: "3 x 5", description: guide.scapulaPull },
      { slug: "negative", name: "Negative Klimmzuege", prescription: "3 x 3 bis 4", description: guide.negativePullup },
    ],
  },
  {
    id: "w5-mon",
    week: 5,
    dayLabel: "Mo",
    fullLabel: "Montag",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 34,
    status: "open",
    description: "Wenn es gut laeuft, darf es leicht flotter sein, aber weiterhin kontrolliert.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "4 x 4 Min", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "4 x 2 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w5-tue",
    week: 5,
    dayLabel: "Di",
    fullLabel: "Dienstag",
    title: "Mobility + Core",
    focus: "Beweglichkeit + Rumpf",
    duration: 18,
    status: "open",
    description: "Leicht bleiben und die Form sauber halten.",
    planTitle: "Mobility + Core",
    exercises: [
      { slug: "mobility", name: "Mobility Flow", prescription: "12 Min", description: guide.mobilityFlow },
      { slug: "plank", name: "Plank", prescription: "3 x 25 Sek", description: guide.plank },
      { slug: "bridge", name: "Glute Bridge", prescription: "2 x 12", description: guide.gluteBridge },
    ],
  },
  {
    id: "w5-wed",
    week: 5,
    dayLabel: "Mi",
    fullLabel: "Mittwoch",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 28,
    status: "open",
    description: "Moderates Tempo und nicht zu aggressiv starten.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "3 x 5 Min", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "3 x 2,5 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w5-thu",
    week: 5,
    dayLabel: "Do",
    fullLabel: "Donnerstag",
    title: "Kraft A",
    focus: "Kraft Unterkoerper + Zug",
    duration: 30,
    status: "open",
    description: "RPE 6 bis 7 und weiter sauber arbeiten.",
    planTitle: "Kraft A",
    exercises: [
      { slug: "squat", name: "Kniebeugen", prescription: "3 x 10", description: guide.squat },
      { slug: "rdl", name: "RDL", prescription: "3 x 10", description: guide.rdl },
      { slug: "row", name: "Rudern", prescription: "3 x 10", description: guide.row },
      { slug: "negative", name: "Negative Klimmzuege", prescription: "3 x 4", description: guide.negativePullup },
    ],
  },
  {
    id: "w5-fri",
    week: 5,
    dayLabel: "Fr",
    fullLabel: "Freitag",
    title: "Pause / Spaziergang",
    focus: "Regeneration",
    duration: 10,
    status: "pause",
    description: "Nur Gassi-Runde und erholen.",
    planTitle: "Pause / Spaziergang",
    exercises: [
      { slug: "walk", name: "Gassi-Runde", prescription: "Locker", description: guide.walkOnly },
    ],
  },
  {
    id: "w5-sat",
    week: 5,
    dayLabel: "Sa",
    fullLabel: "Samstag",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer nach Gefuehl",
    duration: 30,
    status: "open",
    description: "Locker joggen oder gehen nach Gefuehl, aber nicht ueberziehen.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "flow", name: "Lockeres Joggen oder Gehen", prescription: "25 bis 30 Min", description: guide.jogInterval },
    ],
  },
  {
    id: "w5-sun",
    week: 5,
    dayLabel: "So",
    fullLabel: "Sonntag",
    title: "Kraft B",
    focus: "Kraft Beine + Druck + Klimmzug-Basis",
    duration: 30,
    status: "open",
    description: "Stabil und sauber bleiben.",
    planTitle: "Kraft B",
    exercises: [
      { slug: "lunge", name: "Ausfallschritte", prescription: "3 x 10", description: guide.lunge },
      { slug: "pushup", name: "Liegestuetze", prescription: "3 x 8 bis 10", description: guide.pushup },
      { slug: "scapula", name: "Scapula Pulls", prescription: "3 x 5", description: guide.scapulaPull },
      { slug: "hang", name: "Dead Hang", prescription: "3 x 20 bis 30 Sek", description: guide.deadHang },
    ],
  },
  {
    id: "w6-mon",
    week: 6,
    dayLabel: "Mo",
    fullLabel: "Montag",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 33,
    status: "open",
    description: "Nur so laufen, wie es sauber und locker bleibt.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "3 x 6 Min", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "3 x 2 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w6-tue",
    week: 6,
    dayLabel: "Di",
    fullLabel: "Dienstag",
    title: "Mobility + Balance",
    focus: "Beweglichkeit + Balance",
    duration: 18,
    status: "open",
    description: "Leichter Tag fuer Kontrolle und Beweglichkeit.",
    planTitle: "Mobility + Balance",
    exercises: [
      { slug: "mobility", name: "Mobility Flow", prescription: "10 Min", description: guide.mobilityFlow },
      { slug: "balance", name: "Balance Board", prescription: "8 Min", description: guide.balanceBoard },
    ],
  },
  {
    id: "w6-wed",
    week: 6,
    dayLabel: "Mi",
    fullLabel: "Mittwoch",
    title: "Walk-Run mit Hund",
    focus: "Ausdauer + Hund",
    duration: 32,
    status: "open",
    description: "Entspannt laufen und nicht pressen.",
    planTitle: "Walk-Run mit Hund",
    exercises: [
      { slug: "warmup", name: "Warm-up Gehen", prescription: "5 Min", description: guide.walkWarmup },
      { slug: "jog", name: "Locker joggen", prescription: "2 x 8 Min", description: guide.jogInterval },
      { slug: "walk", name: "Gehpause", prescription: "2 x 3 Min", description: guide.walkInterval },
      { slug: "cooldown", name: "Cool-down Gehen", prescription: "5 Min", description: guide.cooldownWalk },
    ],
  },
  {
    id: "w6-thu",
    week: 6,
    dayLabel: "Do",
    fullLabel: "Donnerstag",
    title: "Kraft A",
    focus: "Kraft Unterkoerper + Zug",
    duration: 32,
    status: "open",
    description: "RPE 6 bis 7 mit sauberer Technik.",
    planTitle: "Kraft A",
    exercises: [
      { slug: "goblet", name: "Goblet Squat", prescription: "3 x 8 bis 10", description: guide.gobletSquat },
      { slug: "rdl", name: "RDL", prescription: "3 x 8 bis 10", description: guide.rdl },
      { slug: "row", name: "Rudern", prescription: "3 x 10", description: guide.row },
      { slug: "negative", name: "Negative Klimmzuege", prescription: "3 x 4 bis 5", description: guide.negativePullup },
    ],
  },
  {
    id: "w6-fri",
    week: 6,
    dayLabel: "Fr",
    fullLabel: "Freitag",
    title: "Pause / Spaziergang",
    focus: "Regeneration",
    duration: 10,
    status: "pause",
    description: "Nur Gassi-Runde, kein Extra-Druck.",
    planTitle: "Pause / Spaziergang",
    exercises: [
      { slug: "walk", name: "Gassi-Runde", prescription: "Locker", description: guide.walkOnly },
    ],
  },
  {
    id: "w6-sat",
    week: 6,
    dayLabel: "Sa",
    fullLabel: "Samstag",
    title: "Testlauf",
    focus: "Lauftest + Gefuehl",
    duration: 30,
    status: "open",
    description: "Nur testen, wenn die Beine sich gut anfuehlen. Locker bleiben.",
    planTitle: "Testlauf",
    exercises: [
      { slug: "run", name: "Lockeres Joggen", prescription: "20 bis 30 Min", description: guide.testRun },
      { slug: "option", name: "Alternative Struktur", prescription: "10 Min joggen + 2 bis 3 Min gehen + 10 Min joggen", description: "Nutze diese Variante, wenn durchgehend laufen noch zu hart waere." },
    ],
  },
  {
    id: "w6-sun",
    week: 6,
    dayLabel: "So",
    fullLabel: "Sonntag",
    title: "Kraft B",
    focus: "Kraft Beine + Druck + Klimmzug-Basis",
    duration: 32,
    status: "open",
    description: "Sauber arbeiten und gute Form halten.",
    planTitle: "Kraft B",
    exercises: [
      { slug: "split", name: "Split Squats", prescription: "3 x 8", description: guide.splitSquat },
      { slug: "pushup", name: "Liegestuetze", prescription: "3 x 8", description: guide.pushup },
      { slug: "scapula", name: "Scapula Pulls", prescription: "3 x 5", description: guide.scapulaPull },
      { slug: "hang", name: "Dead Hang", prescription: "3 x 30 bis 40 Sek", description: guide.deadHang },
    ],
  },
];

export const trainings = sessionBlueprints.map((session) =>
  buildSession({
    id: session.id,
    title: session.title,
    focus: session.focus,
    duration: session.duration,
    description: session.description,
    exercises: session.exercises,
  }),
);

export const availableWeeks = [1, 2, 3, 4, 5, 6];

export const weekPlansByWeek = availableWeeks.map((week) =>
  sessionBlueprints
    .filter((session) => session.week === week)
    .map((session) => ({
      id: session.id,
      week,
      dayLabel: session.dayLabel,
      fullLabel: session.fullLabel,
      trainingType: session.planTitle,
      duration: session.duration,
      status: session.status,
      trainingId: session.id,
      isToday: Boolean(session.isToday),
    })),
);

export const mobilityAreas = [
  { key: "shoulder", label: "Schulter", note: "Wie frei fuehlt sich deine Schulter heute an?" },
  { key: "hip", label: "Huefte", note: "Wie beweglich und stabil fuehlt sich deine Huefte an?" },
  { key: "back", label: "Ruecken", note: "Wie locker und belastbar fuehlt sich dein Ruecken an?" },
  { key: "legs", label: "Beine", note: "Wie leicht bewegen sich deine Beine und Oberschenkel?" },
  { key: "neck", label: "Nacken", note: "Wie entspannt und frei ist dein Nacken heute?" },
];

export const initialMobilityRatings = {
  shoulder: 3,
  hip: 4,
  back: 3,
  legs: 4,
  neck: 2,
};

export const initialCompletedExerciseIdsBySessionId = {
  "w1-mon": ["w1-mon-warmup", "w1-mon-jog", "w1-mon-walk", "w1-mon-cooldown"],
  "w1-tue": ["w1-tue-mobility", "w1-tue-plank", "w1-tue-bridge"],
  "w1-wed": ["w1-wed-warmup"],
};
